version: '3.8'
services:
  home-assistant:
    image: homeassistant/home-assistant
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123