
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: EFH Kiefer
  latitude: 50.218925
  longitude: 7.063100
  elevation: 470
  currency: EUR
  unit_system: metric
  time_zone: Europe/Berlin
  temperature_unit: C
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

lovelace:
  mode: yaml

  resources:
    - type: module
      url: local/mdt-jal-aktor-diag.js

  dashboards:
    knx-diagnostics:
      mode: yaml
      filename: dashboards/diagnostics.yaml
      title: Diagnose
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    ground-floor:
      mode: yaml
      filename: dashboards/ground_floor.yaml
      title: 0-Erdgeschoss
      icon: mdi:home-floor-0
    first-floor:
      mode: yaml
      filename: dashboards/first_floor.yaml
      title: 1-Obergeschoss
      icon: mdi:home-floor-1
    second-floor:
      mode: yaml
      filename: dashboards/second_floor.yaml
      title: 2-Spitzboden
      icon: mdi:home-floor-a
    root-top:
      mode: yaml
      filename: dashboards/rooftop.yaml
      title: 3-Dach
      icon: mdi:home-roof

# Text to speech
tts:
  - platform: google_translate

knx: !include_dir_merge_named knx/


sensor:
  - platform: template
    sensors:
      temp_zufluft:
        unique_id: "temp_zuluft"
        friendly_name: "Temperatur Zuluft (kalkuliert)"
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.temperatur_abluft') | float - states('sensor.temperatur_fortluft') | float + states('sensor.temperatur_aussenluft') | float}}"
      wirkungsgrad_lueftung:
        unique_id: "wirkungsgrad_lueftung"
        friendly_name: "Wirkungsgrad Lüftung (kalkuliert)"
        unit_of_measurement: "η"
        value_template: "{{ states('sensor.temp_zufluft') | float / states('sensor.temperatur_abluft') | float}}"

device_tracker:
  - platform: aruba
    host: 10.0.10.1
    username: admin
    password: !secret aruba_password