
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: EFH Kiefer
  latitude: 50.218925
  longitude: 7.063100
  elevation: 470
  currency: EUR
  unit_system: metric
  time_zone: Europe/Berlin
  temperature_unit: C
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

lovelace:
  mode: yaml
  dashboards:
    knx-diagnostics:
      mode: yaml
      filename: dashboards/diagnostics.yaml
      title: Diagnose
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    ground-floor:
      mode: yaml
      filename: dashboards/ground_floor.yaml
      title: Erdgeschoss
      icon: mdi:home-floor-0
    first-floor:
      mode: yaml
      filename: dashboards/first_floor.yaml
      title: Obergeschoss
      icon: mdi:home-floor-1

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

knx: !include_dir_merge_named knx/


#sensor: !include_dir_merge_named sensors/
# switch: 
# - platform: snmp
#   name: ms01_port_2_poe
#   host: 10.0.10.1
#   community: public
#   baseoid: 1.3.6.1.2.1.105.1.1.1.3.1.2
#   payload_on: 1
#   payload_off: 2
#   vartype: INTEGER