
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: EFH Kiefer
  latitude: 50.218925
  longitude: 7.063100
  elevation: 470
  currency: EUR
  unit_system: metric
  time_zone: Europe/Berlin
  temperature_unit: C
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

knx: !include_dir_merge_named knx/