binary_sensor:
  - entity_id: "bs_ls_open_state"
    name: "Hebe/Schiebe links"
    state_address: "3/1/0"
    sync_state: "init"
    device_class: "door"

  - name: "Heizmodus Sommer/Winter"
    state_address: "5/1/0"
    sync_state: "init"
    device_class: "heat"

  - name: "Störung Heizungsaktor EG"
    state_address: "5/2/200"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizungsaktor OG"
    state_address: "5/2/201"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Küche/Wohn/Essbereich"
    state_address: "5/2/20"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"
  
  - name: "Störung Heizkreis Bad EG" 
    state_address: "5/2/40"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis HWR" 
    state_address: "5/2/50"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Diele" 
    state_address: "5/2/60"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"
  
  - name: "Störung Heizkreis Büro" 
    state_address: "5/2/70"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Speisekammer" 
    state_address: "5/2/90"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Kinderzimmer Süd" 
    state_address: "5/2/110"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Kinderzimmer Nord" 
    state_address: "5/2/120"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Bad OG" 
    state_address: "5/2/130"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Schlafzimmer" 
    state_address: "5/2/140"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Ankleide" 
    state_address: "5/2/150"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Störung Heizkreis Flur OG" 
    state_address: "5/2/160"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Bewegung Bad EG"
    state_address: "2/4/40"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung HWR"
    state_address: "2/4/50"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Diele Haustür"
    state_address: "2/4/60"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Diele Treppe"
    state_address: "2/4/61"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Gardarobe"
    state_address: "2/4/80"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Speisekammer"
    state_address: "2/4/90"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Bad OG"
    state_address: "2/4/130"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Flur OG"
    state_address: "2/4/160"
    sync_state: "init"
    device_class: "motion"
