binary_sensor:
  - name: "Hebe/Schiebe links"
    state_address: "3/1/0"
    sync_state: "init"
    device_class: "door"

  - name: "Heizmodus Sommer/Winter"
    state_address: "5/1/0"
    sync_state: "init"
    device_class: "heat"

  - name: "Stoerung Heizungsaktor EG"
    state_address: "5/2/200"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizungsaktor OG"
    state_address: "5/2/201"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Kueche/Wohn/Essbereich"
    state_address: "5/2/20"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"
  
  - name: "Stoerung Heizkreis Bad EG" 
    state_address: "5/2/40"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis HWR" 
    state_address: "5/2/50"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Diele" 
    state_address: "5/2/60"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"
  
  - name: "Stoerung Heizkreis Buero" 
    state_address: "5/2/70"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Speisekammer" 
    state_address: "5/2/90"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Kinderzimmer Sued" 
    state_address: "5/2/110"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Kinderzimmer Nord" 
    state_address: "5/2/120"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Bad OG" 
    state_address: "5/2/130"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Schlafzimmer" 
    state_address: "5/2/140"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Ankleide" 
    state_address: "5/2/150"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Stoerung Heizkreis Flur OG" 
    state_address: "5/2/160"
    sync_state: "init"
    device_class: "problem"
    entity_category: "diagnostic"

  - name: "Bewegung Bad EG"
    state_address: "2/4/40"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung HWR"
    state_address: "2/4/50"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Diele Haustuer"
    state_address: "2/4/60"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Diele Treppe"
    state_address: "2/4/61"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Gardarobe"
    state_address: "2/4/80"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Speisekammer"
    state_address: "2/4/90"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Bad OG"
    state_address: "2/4/130"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Flur OG"
    state_address: "2/4/160"
    sync_state: "init"
    device_class: "motion"

  - name: "Praesenz Einfahrt"
    state_address: "2/4/170"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Einfahrt Sensor 1"
    state_address: "2/4/171"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Einfahrt Sensor 2"
    state_address: "2/4/172"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Einfahrt Sensor 3"
    state_address: "2/4/173"
    sync_state: "init"
    device_class: "motion"

  - name: "Bewegung Einfahrt Sensor 4"
    state_address: "2/4/174"
    sync_state: "init"
    device_class: "motion"

  - name: "Heizung Verdichter/Heizelement aktiv"
    state_address: "0/7/100"
    sync_state: "init"


  ### Lüftung
  - name: "Alarm Ventilator Zuluft"
    state_address: "6/1/40"
    sync_state: "init"
    device_class: "problem"

  - name: "Alarm Ventilator Abluft"
    state_address: "6/1/41"
    sync_state: "init"
    device_class: "problem"
  - name: "Alarm Temeratursensor Fortluft"
    state_address: "6/1/42"
    sync_state: "init"
    device_class: "problem"
  - name: "Alarm Temperatursensor Abluft"
    state_address: "6/1/43"
    sync_state: "init"
    device_class: "problem"
  - name: "Alarm Temperatursensor Aussenluft"
    state_address: "6/1/44"
    sync_state: "init"
    device_class: "problem"