button:
  - name: "Fahrzeitmessung starten Kuechenfenster"
    address: "4/5/0"
  - name: "Fahrzeitmessung starten Hebe/Schiebe links"
    address: "4/5/10"
  - name: "Fahrzeitmessung starten Hebe/Schiebe rechts"
    address: "4/5/20"
  - name: "Fahrzeitmessung starten Bad EG"
    address: "4/5/30"
  - name: "Fahrzeitmessung starten Buero Ostwand"
    address: "4/5/40"
  - name: "Fahrzeitmessung starten Buero Suedwand"
    address: "4/5/50"
  - name: "Fahrzeitmessung starten Speisekammer"
    address: "4/5/60"
  - name: "Fahrzeitmessung starten Kind 1 Suedwand"
    address: "4/5/70"
  - name: "Fahrzeitmessung starten Kind 1 Westwand"
    address: "4/5/80"
  - name: "Fahrzeitmessung starten Kind 2 Westwand"
    address: "4/5/90"
  - name: "Fahrzeitmessung starten Kind 2 Nordwand"
    address: "4/5/100"
  - name: "Fahrzeitmessung starten Bad OG Dusche"
    address: "4/5/110"
  - name: "Fahrzeitmessung starten Bad OG Badewanne Nordwand"
    address: "4/5/120"
  - name: "Fahrzeitmessung starten Bad OG Badewanne Ostwand"
    address: "4/5/130"
  - name: "Fahrzeitmessung starten Schlafzimmer"
    address: "4/5/140"
  - name: "Fahrzeitmessung starten Ankleide"
    address: "4/5/150"
  - name: "Fahrzeitmessung starten Flur OG"
    address: "4/5/160"

  - name: "Beschattung freigeben zentral"
    address: "4/3/200"

  - name: "Heizung relativer Zaehler zuruecksetzen"
    address: "0/7/0"

  - name: "Heizung Zaehlerstaende abfragen"
    address: "0/7/1"