climate:
  - name: "Küchen-/Ess-/Wohnbereich"
    temperature_address: "5/0/20"
    temperature_step: 0.5
    target_temperature_address: "5/3/20"
    target_temperature_state_address: "5/4/20"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Bad EG"
    temperature_address: "5/0/40"
    temperature_step: 0.5
    target_temperature_address: "5/3/40"
    target_temperature_state_address: "5/4/40"
    min_temp: 18.0
    max_temp: 24.0
  
  - name: "HWR"
    temperature_address: "5/0/50"
    temperature_step: 0.5
    target_temperature_address: "5/3/50"
    target_temperature_state_address: "5/4/50"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Diele"
    temperature_address: "5/0/60"
    temperature_step: 0.5
    target_temperature_address: "5/3/60"
    target_temperature_state_address: "5/4/60"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Büro"
    temperature_address: "5/0/70"
    temperature_step: 0.5
    target_temperature_address: "5/3/70"
    target_temperature_state_address: "5/4/70"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Speisekammer"
    temperature_address: "5/0/90"
    temperature_step: 0.5
    target_temperature_address: "5/3/90"
    target_temperature_state_address: "5/4/90"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Kind 1"
    temperature_address: "5/0/100"
    temperature_step: 0.5
    target_temperature_address: "5/3/100"
    target_temperature_state_address: "5/4/100"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Kind 2"
    temperature_address: "5/0/110"
    temperature_step: 0.5
    target_temperature_address: "5/3/110"
    target_temperature_state_address: "5/4/110"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Bad OG"
    temperature_address: "5/0/120"
    temperature_step: 0.5
    target_temperature_address: "5/3/120"
    target_temperature_state_address: "5/4/120"
    min_temp: 18.0
    max_temp: 24.0
  
  - name: "Schlafzimmer"
    temperature_address: "5/0/130"
    temperature_step: 0.5
    target_temperature_address: "5/3/130"
    target_temperature_state_address: "5/4/130"
    min_temp: 18.0
    max_temp: 24.0

  - name: "Ankleide"
    temperature_address: "5/0/140"
    temperature_step: 0.5
    target_temperature_address: "5/3/140"
    target_temperature_state_address: "5/4/140"
    min_temp: 18.0
    max_temp: 24.0
  
  - name: "Flur OG"
    temperature_address: "5/0/150"
    temperature_step: 0.5
    target_temperature_address: "5/3/150"
    target_temperature_state_address: "5/4/150"
    min_temp: 18.0
    max_temp: 24.0

# Diagnostic messages
sensor:
  - name: "diagnostic_text_kitchen_dining_living"
    state_address: "5/5/2"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"

  - name: "Diagnosetext Heizkreis Bad EG"
    state_address: "5/5/3"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"

  - name: "Diagnosetext Heizkreis HWR"
    state_address: "5/5/4"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Diele"
    state_address: "5/5/5"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Büro"
    state_address: "5/5/6"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Speisekammer"
    state_address: "5/5/8"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Kind 1"
    state_address: "5/5/9"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Kind 2"
    state_address: "5/5/10"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Bad OG"
    state_address: "5/5/11"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Schlafzimmer"
    state_address: "5/5/12"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Ankleide"
    state_address: "5/5/13"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Flur OG"
    state_address: "5/5/14"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"