cover:
  - name: "Kuechenfenster"
    move_long_address: "4/0/0"
    stop_address: "4/0/1"
    position_address: "4/1/0"
    position_state_address: "4/2/0"
    angle_address: "4/1/1"
    angle_state_address: "4/2/1"

  - name: "Hebe/Schiebe links"
    move_long_address: "4/0/10"
    stop_address: "4/0/11"
    position_address: "4/1/10"
    position_state_address: "4/2/10"
    angle_address: "4/1/11"
    angle_state_address: "4/2/11"

  - name: "Hebe/Schiebe rechts"
    move_long_address: "4/0/20"
    stop_address: "4/0/21"
    position_address: "4/1/20"
    position_state_address: "4/2/20"
    angle_address: "4/1/21"
    angle_state_address: "4/2/21"

  - name: "Bad EG"
    move_long_address: "4/0/30"
    stop_address: "4/0/31"
    position_address: "4/1/30"
    position_state_address: "4/2/30"
    angle_address: "4/1/31"
    angle_state_address: "4/2/31"

  - name: "Buero Ostwand"
    move_long_address: "4/0/40"
    stop_address: "4/0/41"
    position_address: "4/1/40"
    position_state_address: "4/2/40"
    angle_address: "4/1/41"
    angle_state_address: "4/2/41"

  - name: "Buero Suedwand"
    move_long_address: "4/0/50"
    stop_address: "4/0/51"
    position_address: "4/1/50"
    position_state_address: "4/2/50"
    angle_address: "4/1/51"
    angle_state_address: "4/2/51"

  - name: "Speisekammer"
    move_long_address: "4/0/60"
    stop_address: "4/0/61"
    position_address: "4/1/60"
    position_state_address: "4/2/60"
    angle_address: "4/1/61"
    angle_state_address: "4/2/61"

  - name: "Kind Sued Suedwand"
    move_long_address: "4/0/70"
    stop_address: "4/0/71"
    position_address: "4/1/70"
    position_state_address: "4/2/70"
    device_class: "shutter"
    
  - name: "Kind Sued Westwand"
    move_long_address: "4/0/80"
    stop_address: "4/0/81"
    position_address: "4/1/80"
    position_state_address: "4/2/80"
    device_class: "shutter"
    
  - name: "Kind Nord Westwand"
    move_long_address: "4/0/90"
    stop_address: "4/0/91"
    position_address: "4/1/90"
    position_state_address: "4/2/90"
    device_class: "shutter"

  - name: "Kind Nord Nordwand"
    move_long_address: "4/0/100"
    stop_address: "4/0/101"
    position_address: "4/1/100"
    position_state_address: "4/2/100"
    device_class: "shutter"

  - name: "Bad OG Dusche"
    move_long_address: "4/0/110"
    stop_address: "4/0/111"
    position_address: "4/1/100"
    position_state_address: "4/2/100"
    angle_address: "4/1/111"
    angle_state_address: "4/2/111"
  
  - name: "Bad OG Badewanne Nordwand"
    move_long_address: "4/0/120"
    stop_address: "4/0/121"
    position_address: "4/1/120"
    position_state_address: "4/2/120"
    angle_address: "4/1/121"
    angle_state_address: "4/2/121"
   
  - name: "Bad OG Badewanne Ostwand"
    move_long_address: "4/0/130"
    stop_address: "4/0/131"
    position_address: "4/1/130"
    position_state_address: "4/2/130"
    angle_address: "4/1/131"
    angle_state_address: "4/2/131"
   
  - name: "Schlafzimmer"
    move_long_address: "4/0/140"
    stop_address: "4/0/141"
    position_address: "4/1/140"
    position_state_address: "4/2/140"
    device_class: "shutter"

  - name: "Ankleide"
    move_long_address: "4/0/150"
    stop_address: "4/0/151"
    position_address: "4/1/150"
    position_state_address: "4/2/150"
    angle_address: "4/1/151"
    angle_state_address: "4/2/151"

  - name: "Flur OG"
    move_long_address: "4/0/160"
    stop_address: "4/0/161"
    position_address: "4/1/160"
    position_state_address: "4/2/160"
    angle_address: "4/1/161"
    angle_state_address: "4/2/161"

  - name: "Garagentor"
    move_long_address: "3/3/3"
    stop_address: "3/3/4"
    position_state_address: "3/2/3"
    device_class: "garage"
