light: 
  - name: "kitchen_countertop"
    address: "1/0/0"
    state_address: "1/1/0"

  - name: "kitchen_cookingstation"
    address: "1/0/1"
    state_address: "1/1/1"

  - name: "dining_room"
    address: "1/0/10"
    state_address: "1/1/10"

  - name: "living_room"
    address: "1/0/20"
    state_address: "1/1/20"

  - name: "Licht Wohnbereich TV-Wand"
    address: "1/0/21"
    state_address: "1/1/21"

  - name: "Licht Büro"
    address: "1/0/60"
    state_address: "1/1/60"

  - name: "Licht Kind 1 Decke"
    address: "1/0/90"
    state_address: "1/1/90"
  - name: "Licht Kind 1 Wand"
    address: "1/0/91"
    state_address: "1/1/91"

  - name: "Licht Kind 2 Decke"
    address: "1/0/100"
    state_address: "1/1/100"
  - name: "Licht Kind 2 Wand"
    address: "1/0/101"
    state_address: "1/1/101"

  - name: "Licht Schlafzimmer Decke"
    address: "1/0/120"
    state_address: "1/1/120"
  - name: "Licht Schlafzimmer TV-Wand"
    address: "1/0/121"
    state_address: "1/1/121"
  - name: "Licht Schlafzimmer Nachtlicht links"
    address: "1/0/122"
    state_address: "1/1/122"
  - name: "Licht Schlafzimmer Nachtlicht rechts"
    address: "1/0/123"
    state_address: "1/1/123"

  - name: "Licht Ankleide"
    address: "1/0/130"
    state_address: "1/1/130"

  - name: "Licht Terasse"
    address: "1/0/150"
    state_address: "1/1/150"

  - name: "Licht Garage Stellplätze"
    address: "1/0/170"
    state_address: "1/1/170"

  - name: "Licht Garage Abstellraum"
    address: "1/0/171"
    state_address: "1/1/171"

  - name: "Licht Garage Antrieb"
    address: "1/0/172"
    state_address: "1/1/172"

  - name: "Licht Spitzboden"
    address: "1/0/180"
    state_address: "1/1/180"


switch:
  - name: "Licht Bad EG Handbetrieb"
    address: "2/0/30"
    state_address: "2/1/30"

  - name: "Licht HWR Handbetrieb"
    address: "2/0/40"
    state_address: "2/1/40"

  - name: "Licht Diele Handbetrieb"
    address: "2/0/50"
    state_address: "2/1/50"

  - name: "Licht Gardarobe Handbetrieb"
    address: "2/0/70"
    state_address: "2/1/70"

  - name: "Licht Speisekammer Handbetrieb"
    address: "2/0/80"
    state_address: "2/1/80"

  - name: "Licht Bad OG Handbetrieb"
    address: "2/0/110"
    state_address: "2/1/110"

  - name: "Licht Flur OG Handbetrieb"
    address: "2/0/140"
    state_address: "2/1/140"