number:
  - name: "Lueftung uebersteuern"
    address: "6/0/10"
    type: pulse
    min: 1
    max: 3
    step : 1
    respond_to_read: true
  
  - name: "Lueftung Bypass Schwellwert"
    address: "6/0/30"
    state_address: "6/1/30"
    type: temperature
    min: 15
    max: 30
    step: 1
    mode: slider