sensor:
  - name: "relative Luftfeuchte Essbereich"
    state_address: "6/2/20"
    type: "humidity"
  - name: "CO2 Essbereich"
    state_address: "6/2/22"
    type: "ppm"
  - name: "VOC Essbereich"
    state_address: "6/2/23"
    type: "ppm"

  - name: "relative Luftfeuchte Bad EG"
    state_address: "6/2/40"
    type: "humidity"

  - name: "relative Luftfeuchte HWR"
    state_address: "6/2/50"
    type: "humidity"
  - name: "absolute Luftfeuchte HWR"
    state_address: "6/2/51"
    type: "enthalpy"
  - name: "Taupunkttemperatur HWR"
    state_address: "6/2/54"
    type: "temperature"

  - name: "relative Luftfeuchte Büro"
    state_address: "6/2/70"
    type: "humidity"
  - name: "Taupunkttemperatur Büro"
    state_address: "6/2/74"
    type: "temperature"

  - name: "relative Luftfeuchte Gardarobe"
    state_address: "6/2/80"
    type: "humidity"
  - name: "absolute Luftfeuchte Gardarobe"
    state_address: "6/2/81"
    type: "enthalpy"
  - name: "Taupunkttemperatur Gardarobe"
    state_address: "6/2/84"
    type: "temperature"

  - name: "relative Luftfeuchte Kind 1"
    state_address: "6/2/100"
    type: "humidity"
  - name: "Taupunkttemperatur Kind 2"
    state_address: "6/2/104"
    type: "temperature"

  - name: "relative Luftfeuchte Kind 2"
    state_address: "6/2/110"
    type: "humidity"
  - name: "Taupunkttemperatur Kind 2"
    state_address: "6/2/114"
    type: "temperature"

  - name: "relative Luftfeuchte Bad OG"
    state_address: "6/2/120"
    type: "humidity"
  - name: "Taupunkttemperatur Bad OG"
    state_address: "6/2/124"
    type: "temperature"

  - name: "relative Luftfeuchte Flur OG"
    state_address: "6/2/160"
    type: "humidity"
  - name: "CO2 Flur OG"
    state_address: "6/2/162"
    type: "ppm"
  - name: "VOC Flur OG"
    state_address: "6/2/163"
    type: "ppm"

# illuminance sensor values

  - name: "Bad EG"
    state_address: "2/2/30"
    type: "illuminance"

  - name: "HWR"
    state_address: "2/2/40"
    type: "illuminance"

  - name: "Diele PM1"
    state_address: "2/2/50"
    type: "illuminance"

  - name: "Diele PM2"
    state_address: "2/2/51"
    type: "illuminance"

  - name: "Gardarobe"
    state_address: "2/2/70"
    type: "illuminance"

  - name: "Speisekammer"
    state_address: "2/2/80"
    type: "illuminance"

  - name: "Bad OG"
    state_address: "2/2/110"
    type: "illuminance"

  - name: "Flur OG"
    state_address: "2/2/140"
    type: "illuminance"