sensor:
  ###############################
  # Luftfeuchte   0/0/xxx
  ###############################
  - name: "relative Luftfeuchte Essbereich"
    state_address: "0/0/1"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Bad EG"
    state_address: "0/0/40"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte HWR"
    state_address: "0/0/50"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "absolute Luftfeuchte HWR"
    state_address: "0/0/51"
    sync_state: "init"
    type: "enthalpy"
    state_class: measurement


  - name: "relative Luftfeuchte Buero"
    state_address: "0/0/70"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Gardarobe"
    state_address: "0/0/80"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "absolute Luftfeuchte Gardarobe"
    state_address: "0/0/81"
    sync_state: "init"
    type: "enthalpy"
    state_class: measurement


  - name: "relative Luftfeuchte Kind 1"
    state_address: "0/0/100"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Kind 2"
    state_address: "0/0/110"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Bad OG"
    state_address: "0/0/130"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Flur OG"
    state_address: "0/0/160"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  - name: "relative Luftfeuchte Garage"
    state_address: "0/0/200"
    sync_state: "init"
    type: "humidity"
    state_class: measurement


  ###############################
  # Taupunkt    0/2/xxx
  ###############################
  - name: "Taupunkttemperatur HWR"
    state_address: "0/2/50"
    sync_state: "init"
    type: "temperature"
  
  - name: "Taupunkttemperatur Buero"
    state_address: "0/2/70"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Gardarobe"
    state_address: "0/2/80"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Kind 1"
    state_address: "0/2/100"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Kind 2"
    state_address: "0/2/110"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Bad OG"
    state_address: "0/2/120"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Garage"
    state_address: "0/2/200"
    sync_state: "init"
    type: "temperature"
    


  ##############################
  # Helligkeit    0/4/xxx
  ###############################
  - name: "Bad EG"
    state_address: "0/4/30"
    sync_state: "init"
    type: "illuminance"

  - name: "HWR"
    state_address: "0/4/40"
    sync_state: "init"
    type: "illuminance"

  - name: "Diele PM1"
    state_address: "0/4/50"
    sync_state: "init"
    type: "illuminance"

  - name: "Diele PM2"
    state_address: "0/4/51"
    sync_state: "init"
    type: "illuminance"

  - name: "Gardarobe"
    state_address: "0/4/70"
    sync_state: "init"
    type: "illuminance"

  - name: "Speisekammer"
    state_address: "0/4/80"
    sync_state: "init"
    type: "illuminance"

  - name: "Bad OG"
    state_address: "0/4/110"
    sync_state: "init"
    type: "illuminance"

  - name: "Flur OG"
    state_address: "0/4/140"
    sync_state: "init"
    type: "illuminance"


  ###############################
  # VOC    0/5/xxx
  ###############################
  - name: "VOC Essbereich"
    state_address: "0/5/23"
    sync_state: "init"
    type: "ppm"
    state_class: measurement


  - name: "VOC Flur OG"
    state_address: "0/5/163"
    sync_state: "init"
    type: "ppm"
    state_class: measurement


  ###############################
  # CO2    0/6/xxx
  ###############################
  - name: "CO2 Essbereich"
    state_address: "0/5/22"
    sync_state: "init"
    type: "ppm"

  - name: "CO2 Flur OG"
    state_address: "0/5/162"
    sync_state: "init"
    type: "ppm"

  ###############################
  # Diagnostic heating
  ###############################

  - name: "Diagnosetext Heizkreis Kuechen-/Ess-/Wohnbereich"
    state_address: "5/5/2"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"

  - name: "Diagnosetext Heizkreis Bad EG"
    state_address: "5/5/3"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"

  - name: "Diagnosetext Heizkreis HWR"
    state_address: "5/5/4"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Diele"
    state_address: "5/5/5"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Buero"
    state_address: "5/5/6"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Speisekammer"
    state_address: "5/5/8"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Kind 1"
    state_address: "5/5/9"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Kind 2"
    state_address: "5/5/10"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Bad OG"
    state_address: "5/5/11"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Schlafzimmer"
    state_address: "5/5/12"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Ankleide"
    state_address: "5/5/13"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"
  
  - name: "Diagnosetext Heizkreis Flur OG"
    state_address: "5/5/14"
    sync_state: "init"
    type: "string"
    entity_category: "diagnostic"

  ###############################
  # Diagnostic covers
  ###############################
  
  - name: "Diagnosetext JA1"
    state_address: "4/4/201"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext JA2"
    state_address: "4/4/202"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext JA3"
    state_address: "4/4/203"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Kuechenfenster"
    state_address: "4/4/0"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Hebe/Schiebe links"
    state_address: "4/4/10"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Hebe/Schiebe rechts"
    state_address: "4/4/20"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Bad EG"
    state_address: "4/4/30"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Buero Ostwand"
    state_address: "4/4/40"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Buero Suedwand"
    state_address: "4/4/50"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Speisekammer"
    state_address: "4/4/60"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Kind 1 Suedwand"
    state_address: "4/4/70"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Kind 1 Westwand"
    state_address: "4/4/80"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Kind 2 Westwand"
    state_address: "4/4/90"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Kind 2 Nordwand"
    state_address: "4/4/100"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Bad OG Dusche"
    state_address: "4/4/110"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Bad OG Badewanne Nordwand"
    state_address: "4/4/120"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Bad OG Badewanne Ostwand"
    state_address: "4/4/130"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Schlafzimmer"
    state_address: "4/4/140"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Ankleide"
    state_address: "4/4/150"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"

  - name: "Diagnosetext Flur OG"
    state_address: "4/4/160"
    type: "string"
    sync_state: "init"
    entity_category: "diagnostic"



  - name: Heizung Zaehlerstand relativ
    state_address: "0/7/2"
    type: active_energy_kwh
    sync_state: "init"
    state_class: total
    
  - name: Heizung Zaehlerstand Total
    state_address: "0/7/3"
    type: active_energy_kwh
    sync_state: "init"
    state_class: total_increasing

  - name: Heizung Wirkleistung Gesamt
    state_address: "0/7/4"
    type: power
    sync_state: "init"
    state_class: measurement
    
  - name: Heizung Wirkleistung L1
    state_address: "0/7/5"
    type: power
    sync_state: "init"
    state_class: measurement

  - name: Heizung Wirkleistung L2
    state_address: "0/7/6"
    type: power
    sync_state: "init"
    state_class: measurement
  
  - name: Heizung Wirkleistung L3
    state_address: "0/7/7"
    type: power
    sync_state: "init"
    state_class: measurement
    

  - name: Heizung Spannung L1
    state_address: "0/7/8"
    type: electric_potential
    sync_state: "init"
    state_class: measurement
    
  - name: Heizung Spannung L2
    state_address: "0/7/9"
    type: electric_potential
    sync_state: "init"
    state_class: measurement
  
  - name: Heizung Spannung L3
    state_address: "0/7/10"
    type: electric_potential
    sync_state: "init"
    state_class: measurement


  - name: Heizung Stromstaerke L1
    state_address: "0/7/11"
    type: electric_current
    sync_state: "init"
    state_class: measurement
    
  - name: Heizung Stromstaerke L2
    state_address: "0/7/12"
    type: electric_current
    sync_state: "init"
    state_class: measurement
  
  - name: Heizung Stromstaerke L3
    state_address: "0/7/13"
    type: electric_current
    sync_state: "init"
    state_class: measurement



  - name: Heizung Leistungsfaktor L1
    state_address: "0/7/14"
    type: powerfactor
    sync_state: "init"
    state_class: measurement
    
  - name: Heizung Leistungsfaktor L2
    state_address: "0/7/15"
    type: powerfactor
    sync_state: "init"
    state_class: measurement
  
  - name: Heizung Leistungsfaktor L3
    state_address: "0/7/16"
    type: powerfactor
    sync_state: "init"
    state_class: measurement



  - name: Heizung Wirkenergie L1
    state_address: "0/7/17"
    type: active_energy_kwh
    sync_state: "init"
    state_class: measurement
    
  - name: Heizung Wirkenergie L2
    state_address: "0/7/18"
    type: active_energy_kwh
    sync_state: "init"
    state_class: measurement
  
  - name: Heizung Wirkenergie L3
    state_address: "0/7/19"
    type: active_energy_kwh
    sync_state: "init"
    state_class: measurement


  - name: Betriebsstunden Licht Kueche Arbeitsplatte
    state_address: "1/7/0"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing


  - name: Betriebsstunden Licht Kueche Kochinsel
    state_address: "1/7/1"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Essbereich
    state_address: "1/7/20"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Wohnzimmer Couch
    state_address: "1/7/2"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Wohnzimmer TV-Wand
    state_address: "1/7/21"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Bad EG
    state_address: "1/7/30"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht HWR
    state_address: "1/7/40"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Diele
    state_address: "1/7/50"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Buero
    state_address: "1/7/60"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Gardarobe
    state_address: "1/7/70"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Speisekammer
    state_address: "1/7/80"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Kind Nord Decke
    state_address: "1/7/90"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Nord Wandleuchte
    state_address: "1/7/91"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Sued Decke
    state_address: "1/7/100"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Sued Wandleuchte
    state_address: "1/7/101"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Bad OG Decke
    state_address: "1/7/110"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Bad OG Wandleuchten
    state_address: "1/7/111"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Schlafzimmer Decke
    state_address: "1/7/120"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Schlafzimmer TV-Wand
    state_address: "1/7/121"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Schlafzimmer Nachtlicht links
    state_address: "1/7/122"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Schlafzimmer Nachtlicht rechts
    state_address: "1/7/123"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Ankleide
    state_address: "1/7/130"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Flur OG
    state_address: "1/7/140"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing

  - name: Betriebsstunden Licht Spitzboden
    state_address: "1/7/180"
    type: long_delta_timesec
    sync_state: "init"
    state_class: total_increasing