sensor:
  ###############################
  # Luftfeuchte   0/0/xxx
  ###############################
  - name: "relative Luftfeuchte Essbereich"
    state_address: "0/0/1"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Bad EG"
    state_address: "0/0/40"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte HWR"
    state_address: "0/0/50"
    sync_state: "init"
    type: "humidity"

  - name: "absolute Luftfeuchte HWR"
    state_address: "0/0/51"
    sync_state: "init"
    type: "enthalpy"

  - name: "relative Luftfeuchte Büro"
    state_address: "0/0/70"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Gardarobe"
    state_address: "0/0/80"
    sync_state: "init"
    type: "humidity"

  - name: "absolute Luftfeuchte Gardarobe"
    state_address: "0/0/81"
    sync_state: "init"
    type: "enthalpy"

  - name: "relative Luftfeuchte Kind 1"
    state_address: "0/0/100"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Kind 2"
    state_address: "0/0/110"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Bad OG"
    state_address: "0/0/130"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Flur OG"
    state_address: "0/0/160"
    sync_state: "init"
    type: "humidity"

  - name: "relative Luftfeuchte Garage"
    state_address: "0/0/200"
    sync_state: "init"
    type: "humidity"


  ###############################
  # Taupunkt    0/2/xxx
  ###############################
  - name: "Taupunkttemperatur HWR"
    state_address: "0/2/50"
    sync_state: "init"
    type: "temperature"
  
  - name: "Taupunkttemperatur Büro"
    state_address: "0/2/70"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Gardarobe"
    state_address: "0/2/80"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Kind 1"
    state_address: "0/2/100"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Kind 2"
    state_address: "0/2/110"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Bad OG"
    state_address: "0/2/120"
    sync_state: "init"
    type: "temperature"

  - name: "Taupunkttemperatur Garage"
    state_address: "0/2/200"
    sync_state: "init"
    type: "temperature"


  ##############################
  # Helligkeit    0/4/xxx
  ###############################
  - name: "Bad EG"
    state_address: "0/4/30"
    sync_state: "init"
    type: "illuminance"

  - name: "HWR"
    state_address: "0/4/40"
    sync_state: "init"
    type: "illuminance"

  - name: "Diele PM1"
    state_address: "0/4/50"
    sync_state: "init"
    type: "illuminance"

  - name: "Diele PM2"
    state_address: "0/4/51"
    sync_state: "init"
    type: "illuminance"

  - name: "Gardarobe"
    state_address: "0/4/70"
    sync_state: "init"
    type: "illuminance"

  - name: "Speisekammer"
    state_address: "0/4/80"
    sync_state: "init"
    type: "illuminance"

  - name: "Bad OG"
    state_address: "0/4/110"
    sync_state: "init"
    type: "illuminance"

  - name: "Flur OG"
    state_address: "0/4/140"
    sync_state: "init"
    type: "illuminance"


  ###############################
  # VOC    0/5/xxx
  ###############################
  - name: "VOC Essbereich"
    state_address: "0/5/23"
    sync_state: "init"
    type: "ppm"

  - name: "VOC Flur OG"
    state_address: "0/5/163"
    sync_state: "init"
    type: "ppm"


  ###############################
  # CO2    0/6/xxx
  ###############################
  - name: "CO2 Essbereich"
    state_address: "0/6/22"
    sync_state: "init"
    type: "ppm"

  - name: "CO2 Flur OG"
    state_address: "0/6/162"
    sync_state: "init"
    type: "ppm"

