switch:
  - name: "Beschattung Automatik Kuechenfenster"
    address: "4/3/1"
    state_address: "4/3/0"
    invert: true

  - name: "Beschattung Automatik Hebe/Schiebe links"
    address: "4/3/11"
    state_address: "4/3/10"
    invert: true

  - name: "Beschattung Automatik Hebe/Schiebe rechts"
    address: "4/3/21"
    state_address: "4/3/20"
    invert: true

  - name: "Beschattung Automatik Buero Ostfenster"
    address: "4/3/41"
    state_address: "4/3/40"
    invert: true

  - name: "Beschattung Automatik Buero Suedfenster"
    address: "4/3/51"
    state_address: "4/3/50"
    invert: true

  - name: "Beschattung Automatik Speisekammer"
    address: "4/3/61"
    state_address: "4/3/60"
    invert: true

  - name: "Beschattung Automatik Kind Sued Suedfenster"
    address: "4/3/71"
    state_address: "4/3/70"
    invert: true

  - name: "Beschattung Automatik Kind Sued Westfenster"
    address: "4/3/81"
    state_address: "4/3/80"
    invert: true

  - name: "Beschattung Automatik Kind Nord Westfenster"
    address: "4/3/91"
    state_address: "4/3/90"
    invert: true

  - name: "Beschattung Automatik Kind Nord Nordfenster"
    address: "4/3/101"
    state_address: "4/3/100"
    invert: true

  - name: "Beschattung Automatik Bad OG Ostfenster"
    address: "4/3/131"
    state_address: "4/3/130"
    invert: true

  - name: "Beschattung Automatik Schlafzimmer"
    address: "4/3/141"
    state_address: "4/3/140"
    invert: true

  - name: "Beschattung Automatik Ankleide"
    address: "4/3/151"
    state_address: "4/3/150"
    invert: true

  - name: "Beschattung Automatik Flur OG"
    address: "4/3/161"
    state_address: "4/3/160"
    invert: true



  - name: "Licht Bad EG Handbetrieb"
    address: "2/0/30"
    state_address: "2/1/30"

  - name: "Licht HWR Handbetrieb"
    address: "2/0/40"
    state_address: "2/1/40"

  - name: "Licht Diele Handbetrieb"
    address: "2/0/50"
    state_address: "2/1/50"

  - name: "Licht Gardarobe Handbetrieb"
    address: "2/0/70"
    state_address: "2/1/70"

  - name: "Licht Speisekammer Handbetrieb"
    address: "2/0/80"
    state_address: "2/1/80"

  - name: "Licht Bad OG Handbetrieb"
    address: "2/0/110"
    state_address: "2/1/110"

  - name: "Licht Flur OG Handbetrieb"
    address: "2/0/140"
    state_address: "2/1/140"


  - name: "Lueftung automatik"
    address: "6/0/11"
    invert: true