switch:
  - name: "Beschattung Kuechenfenster sperren"
    address: "4/3/1"
    state_address: "4/3/0"

  - name: "Beschattung Hebe/Schiebe links sperren"
    address: "4/3/11"
    state_address: "4/3/10"

  - name: "Beschattung Hebe/Schiebe rechts sperren"
    address: "4/3/21"
    state_address: "4/3/20"

  - name: "Beschattung Buero Ostfenster sperren"
    address: "4/3/41"
    state_address: "4/3/40"

  - name: "Beschattung Buero Suedfenster sperren"
    address: "4/3/51"
    state_address: "4/3/50"

  - name: "Beschattung Speisekammer sperren"
    address: "4/3/61"
    state_address: "4/3/60"

  - name: "Beschattung Kind Sued Suedfenster sperren"
    address: "4/3/71"
    state_address: "4/3/70"

  - name: "Beschattung Kind Sued Westfenster sperren"
    address: "4/3/81"
    state_address: "4/3/80"

  - name: "Beschattung Kind Nord Westfenster sperren"
    address: "4/3/91"
    state_address: "4/3/90"

  - name: "Beschattung Bad OG Ostfenster sperren"
    address: "4/3/131"
    state_address: "4/3/130"

  - name: "Beschattung Schlafzimmer sperren"
    address: "4/3/141"
    state_address: "4/3/140"

  - name: "Beschattung Ankleide sperren"
    address: "4/3/151"
    state_address: "4/3/150"

  - name: "Beschattung Flur OG sperren"
    address: "4/3/161"
    state_address: "4/3/160"

  

  - name: "Licht Bad EG Handbetrieb"
    address: "2/0/30"
    state_address: "2/1/30"

  - name: "Licht HWR Handbetrieb"
    address: "2/0/40"
    state_address: "2/1/40"

  - name: "Licht Diele Handbetrieb"
    address: "2/0/50"
    state_address: "2/1/50"

  - name: "Licht Gardarobe Handbetrieb"
    address: "2/0/70"
    state_address: "2/1/70"

  - name: "Licht Speisekammer Handbetrieb"
    address: "2/0/80"
    state_address: "2/1/80"

  - name: "Licht Bad OG Handbetrieb"
    address: "2/0/110"
    state_address: "2/1/110"

  - name: "Licht Flur OG Handbetrieb"
    address: "2/0/140"
    state_address: "2/1/140"



  ### Lüftung
  - name: "Lueftung Partymodus"
    address: "6/0/11"

  - name: "Bypass Klappe öffnen"
    address: "6/0/31"
    state_address: "6/1/31"
